import type { Level, Module, Section } from './types'; // CHANGED (S9): Localized no longer needed (stub helper removed — all modules authored).
// CHANGED (S1): golden module M5 authored. CHANGED (S9): M1–M13 all authored — no stubs remain.
import { m5 } from './modules/m5-generics-conditional-types';
// CHANGED (S2): Section I authored — M1 (structural typing) + M2 (narrowing), each with a signature sim.
import { m1 } from './modules/m1-structural-typing';
import { m2 } from './modules/m2-narrowing';
// CHANGED (S3): Section II deepened — M4 (generics) + M6 (mapped/template-literal types), each with a sim.
import { m4 } from './modules/m4-generics';
import { m6 } from './modules/m6-mapped-template-literals';
// CHANGED (S4): Section II capstone — M7 (utility types) authored with the ★ utility-type decoder sim.
import { m7 } from './modules/m7-utility-types';
// CHANGED (S5): Section I completed — M3 (Functions, Overloads & Variance), diagram-first (no sim).
import { m3 } from './modules/m3-functions-variance';
// CHANGED (S6): Section III opened — M8 (Decorators & Metadata, NestJS · Angular), diagram-first (no sim).
import { m8 } from './modules/m8-decorators-metadata';
// CHANGED (S7): Section III continued — M9 (DTO validation) + M10 (RxJS/signals), diagram-first (no sims).
import { m9 } from './modules/m9-dto-validation';
import { m10 } from './modules/m10-rxjs-signals';
// CHANGED (S8): Section IV opened — M11 (tsconfig & strictness) + M12 (modules & resolution), each with a ★ signature sim.
import { m11 } from './modules/m11-tsconfig-strictness';
import { m12 } from './modules/m12-modules-resolution';
// CHANGED (S9): Section IV completed — M13 (Declaration Files & Publishing Types), diagram-first (no sim). All 13 modules authored.
import { m13 } from './modules/m13-declaration-files';

/*
 * concepts.ts — the SINGLE SOURCE OF TRUTH (CLAUDE.md §2, §4).
 * 4 sections · 13 modules. S1 shipped Section II's golden M5; S2 added Section I's M1 + M2; S3 deepened
 * Section II with M4 (Generics) + M6 (Mapped & Template-Literal Types); S4 completed Section II with M7
 * (Utility Types); S5 authored Section I's last module M3 (Functions, Overloads & Variance) and shipped
 * the meta/bundle split; S6 opened Section III with M8 (Decorators & Metadata); S7 completed Section III
 * with M9 (DTO Validation) + M10 (RxJS/Signals); S8 opened Section IV with M11 (tsconfig & strictness)
 * + M12 (modules & resolution), each carrying a ★ signature sim; S9 completed Section IV and the whole
 * curriculum with M13 (declaration files & publishing types), diagram-first. All 13 modules are now
 * authored — no stubs remain.
 * concepts.ts stays the SSOT: the eager chrome now reads the slim nav/search index (src/data/meta.ts,
 * generated by scripts/genMeta.ts) so module bodies stay out of the initial bundle; only the lazy
 * ModulePage imports full bodies from here (CLAUDE.md §2 · standard §4.4).
 */

export const sections: Section[] = [
  {
    id: 's1-type-system',
    roman: 'I',
    title: { en: 'The Type System', uk: 'Система типів' },
    accent: '#3178c6', // TypeScript blue
    blurb: {
      en: 'How TypeScript reasons: structural typing, assignability, narrowing, functions and variance.',
      uk: 'Як міркує TypeScript: structural typing, assignability, narrowing, функції та variance.',
    },
  },
  {
    id: 's2-type-level',
    roman: 'II',
    title: { en: 'Type-Level Programming', uk: 'Type-Level програмування' },
    accent: '#1593ad', // teal
    blurb: {
      en: 'The type system as a language: generics, conditional types, infer, mapped & utility types.',
      uk: 'Система типів як мова: generics, conditional types, infer, mapped- та utility-типи.',
    },
  },
  {
    id: 's3-applied',
    roman: 'III',
    title: { en: 'Applied TypeScript', uk: 'Прикладний TypeScript' },
    accent: '#6a7fe0', // indigo-blue
    blurb: {
      en: 'TypeScript in your stack: decorators & DI, DTO validation, typing RxJS and Angular signals.',
      uk: 'TypeScript у вашому стеку: decorators і DI, валідація DTO, типізація RxJS та Angular signals.',
    },
  },
  {
    id: 's4-compiler',
    roman: 'IV',
    title: { en: 'Compiler & Tooling', uk: 'Компілятор та інструменти' },
    accent: '#4f86a8', // steel blue
    blurb: {
      en: 'tsconfig & strictness, module resolution, project references, declaration files and the build.',
      uk: 'tsconfig і strictness, module resolution, project references, declaration files та збірка.',
    },
  },
];

// CHANGED (S9): the `stub()` helper + `StubInput` type were removed — all 13 modules are now authored,
// so the navigable-skeleton scaffold is no longer needed. `isAuthored()` (topics.length > 0) stays as
// the renderer's guard. Restore the helper from git history if a future section adds stub modules.
export const modules: Module[] = [
  // ── Section I · The Type System ──────────────────────────────────────────
  m1, // ★ authored (S2) — Structural Typing & Assignability
  m2, // ★ authored (S2) — Narrowing & Control-Flow Analysis
  m3, // authored (S5) — Functions, Overloads & Variance (diagram-first, no sim)

  // ── Section II · Type-Level Programming ───────────────────────────────────
  m4, // ★ authored (S3) — Generic Functions & Classes
  m5, // ★ GOLDEN — fully authored (Generics & Conditional Types)
  m6, // ★ authored (S3) — Mapped & Template-Literal Types
  m7, // ★ authored (S4) — Built-in Utility Types, Decoded

  // ── Section III · Applied TypeScript ──────────────────────────────────────
  m8, // authored (S6) — Decorators & Metadata (NestJS · Angular), diagram-first (no sim)
  m9, // authored (S7) — DTOs, Validation & API Boundaries, diagram-first (no sim)
  m10, // authored (S7) — Typing RxJS, Signals & Component State, diagram-first (no sim) — Section III complete

  // ── Section IV · Compiler & Tooling ───────────────────────────────────────
  m11, // ★ authored (S8) — tsconfig & the Strictness Model
  m12, // ★ authored (S8) — Modules, Resolution & Project References
  m13, // authored (S9) — Declaration Files & Publishing Types, diagram-first (no sim) — Section IV & the curriculum complete
];

// ── Lookups ────────────────────────────────────────────────────────────────
const moduleById = new Map(modules.map((m) => [m.id, m]));
const sectionById = new Map(sections.map((s) => [s.id, s]));

export function getModule(id: string): Module | undefined {
  return moduleById.get(id);
}
export function getSection(id: string): Section | undefined {
  return sectionById.get(id);
}
export function modulesBySection(sectionId: string): Module[] {
  return modules.filter((m) => m.section === sectionId).sort((a, b) => a.order - b.order);
}
/** Previous / next module in global order (by `num`). */
export function adjacentModules(id: string): { prev?: Module; next?: Module } {
  const ordered = [...modules].sort((a, b) => a.num - b.num);
  const i = ordered.findIndex((m) => m.id === id);
  if (i === -1) return {};
  return { prev: ordered[i - 1], next: ordered[i + 1] };
}
/** A module is "authored" (vs a navigable stub) once it has topics. */
export function isAuthored(m: Module): boolean {
  return m.topics.length > 0;
}

export const LEVELS: Level[] = ['beginner', 'middle', 'senior', 'staff'];

export const COUNTS = {
  sections: sections.length,
  modules: modules.length,
  sims: modules.filter((m) => m.signature).length,
};
